### ISSUE TITLE
Opening modalbox in IRRE content elements

### ISSUE THREAD

**Issue by lucmuller** [quellenform/t3x-iconpack#10]
When a content is placed in a IRRE such as in ext:news, the modalbox that allow the selection of the icon is not opening
I do not identifies any javascript error not network request error.

TYPO3 version : 11.5.26
IconPack version : 0.2.1
![image](https://github.com/quellenform/t3x-iconpack/assets/1927963/a41d0562-367f-470b-a8cf-7a830a97441f)

**Comment by stephankellermayr** [comment]
Thanks for your feedback! That is correct, I can confirm this as a bug...

**Comment by stephankellermayr** [comment]
This bug should be fixed with the latest version. Thanks again for your feedback and let me know if you still have problems. All the best!
