### ISSUE TITLE
Option to remove default CSS

### ISSUE THREAD

**Issue by KreativeKrise** [quellenform/t3x-iconpack#11]
Would it be possible to add an option to disable the `EXT:iconpack/Resources/Public/Css/Iconpack.min.css`?
With the currently used method `$pageRenderer->addCssFile();` it's not possible to remove it.

Another way would be using the [asset collector](https://docs.typo3.org/m/typo3/reference-coreapi/11.5/en-us/ApiOverview/Assets/Index.html) class instead. Then it would be possible to use the `removeStyleSheet()` function.

**Comment by stephankellermayr** [comment]
That would be possible, of course. Also the use of _Asset Collector_ sounds like a good idea. In what way would this variant be better than the one used so far? Do you have a concrete suggestion?

Just out of interest: What exactly is the idea behind including the CSS file as an option? This only affects the appearance of all SVG icons in the backend that are displayed by EXT:iconpack, and they should always be positioned the same, shouldn't they?

**Comment by KreativeKrise** [comment]
> In what way would this variant be better than the one used so far?

I'm not 100% sure. That was a suggestion from the TYPO3 Slack, that this should be migrated. But one advantage would be, that you could remove the Stylesheet with the `removeStyleSheet()` function, if a identifier was used on the `addStyleSheet()` function.

> Just out of interest: What exactly is the idea behind including the CSS file as an option? This only affects the appearance of all SVG icons in the backend that are displayed by EXT:iconpack, and they should always be positioned the same, shouldn't they?

My issue is, that this CSS is rendered in the frontend.

```
svg[data-iconfig],
img[data-iconfig] {
  width: auto;
  height: 1em;
  vertical-align: -0.125em;
  margin-right: 0.125em;
}
```

As a workaround I could of course overwrite it, but it would be cleaner if it just could be disabled or removed.

**Comment by stephankellermayr** [comment]
Unfortunately, I did not succeed in implementing the AssetCollector at this point (and I'm not quite sure if this is the right way to do it in this use case). I always received a deprecated message: "_Deprecation: #85735 - Various method and property in DocumentTemplate"_.

But I hope I could solve this in the meantime anyway by making the StyleSheet optional.

**Comment by KreativeKrise** [comment]
Thanks for outsourcing the StyleSheet to TypoScript! :)
