### ISSUE TITLE
Icons for sys_category

### ISSUE THREAD

**Issue by t3brightside** [quellenform/t3x-iconpack#12]
Cool extension, well done @stephankellermayr !

Surely easy to extend but would be cool to have the feature of adding icons to categories.

**Comment by t3brightside** [comment]
Added a pull request if there's any interest.

**Comment by stephankellermayr** [comment]
@t3brightside Thank you for your interest in the extension (apparently there are people who find it helpful after all), your praise and your feedback!

Your suggestion looks like a good idea, can't see any downside either, and I'll look at it in detail shortly.
