### ISSUE TITLE
HiRes Icon for RTE is missing

### ISSUE THREAD

**Issue by christianhaendel** [quellenform/t3x-iconpack#16]
In TYPO3-Backend there is a detection for 4K displays in JavaScript. But the 4K Icons aren't available in the extension.

The Icons Paths is changed via Javascript from
/typo3conf/ext/iconpack/Resources/Public/JavaScript/v11/CKEditor/icons/
to
/typo3conf/ext/iconpack/Resources/Public/JavaScript/v11/CKEditor/icons/hidpi 

The Icon-Path hidpi isn't included in the extension. Please fix.
A current workarround is to include the following htaccess rule in your TYPO3 htaccess
`RedirectMatch 301 /typo3conf/ext/iconpack/Resources/Public/JavaScript/v11/CKEditor/icons/hidpi/(.*) /typo3conf/ext/iconpack/Resources/Public/JavaScript/v11/CKEditor/icons//$1`
But a long Termin solution is needed.

**Comment by stephankellermayr** [comment]
Thanks for your feedback! ...fixed with commit d13ac36
