### ISSUE TITLE
Missing argument when calling YamlFileLoader in version 13.3+

### ISSUE THREAD

**Issue by gmt-it** [quellenform/t3x-iconpack#23]
Hello,

after installing at 13.3 backend crashes with the following error:

(1/1) ArgumentCountError
Too few arguments to function TYPO3\CMS\Core\Configuration\Loader\YamlFileLoader::__construct(), 0 passed in /var/www/html/vendor/quellenform/t3x-iconpack/Classes/EventListener/IconpackPrepareConfigurationForEditor.php on line 55 and exactly 1 expected.

BR

Guido

**Comment by stephankellermayr** [comment]
@gmt-it Thank you for reporting this problem. Something seems to have changed here in the core with version 13.3 regarding `TYPO3\CMS\Core\Configuration\Loader\Psr\Log\LoggerInterface`: https://github.com/TYPO3/typo3/commit/8f57cba28ffcbf4d9a2c5eea6f3d969be7ba7256

Apparently the class must be called differently here.

Do you have a PR for this?

**Comment by gmt-it** [comment]
No. No PR yet.

**Comment by stephankellermayr** [comment]
Fixed with version 1.1.8 (36ac5b0). Thanks for your feedback!
