### ISSUE TITLE
Error on installation with TYPO3 13.3

### ISSUE THREAD

**Issue by wini2** [quellenform/t3x-iconpack#24]
After installation (with composer req quellenform/t3x-iconpack) of Iconpack and iconpack_bootstrap (composer req quellenform/t3x-iconpack-bootstrap), the following error-message shows up

Too few arguments to function TYPO3\CMS\Core\Configuration\Loader\YamlFileLoader::__construct(), 0 passed in /home/www/mysite/vendor/quellenform/t3x-iconpack/Classes/IconpackRegistry.php on line 72 and exactly 1 expected

Probably the same cause as described in https://github.com/quellenform/t3x-iconpack/issues/23

**Comment by stephankellermayr** [comment]
@wini2 Thank you for your feedback! This is definitely related to #23 and concerns the same cause. Bugfix is on the way.

**Comment by stephankellermayr** [comment]
Fixed with version 1.1.8 (36ac5b0). Thanks for your feedback!
