### ISSUE TITLE
How to show options in own iconpack

### ISSUE THREAD

**Issue by gmt-it** [quellenform/t3x-iconpack#27]
Hello Stephan.

I built my own icon pack. It works very well following the instructions in the documentation. I can insert my icons and they are displayed.
Is there a secret to how the options are displayed? I used example 3 (https://docs.typo3.org/p/quellenform/t3x-iconpack/main/en-us/Tutorials/YamlExamples.html). But the options are not displayed.

TIA

Guido

**Comment by stephankellermayr** [comment]
Since I don't know the contents of your YAML file, I can't tell you what you're doing wrong. Actually, there are few secrets here, but maybe this example will help you: https://github.com/quellenform/t3x-iconpack-fontawesome/blob/main/Configuration/Iconpack/FontAwesome6.yaml

**Comment by gmt-it** [comment]
Stephan,

I have used this template in part. Something is wrong, I don't know where. The CSS file is not being read either.

[my_icon.yaml.txt](https://github.com/user-attachments/files/17535203/my_icon.yaml.txt)

**Comment by stephankellermayr** [comment]
At first glance, it doesn't look fundamentally wrong.

However, when using YAML, you must pay close attention to the indents. These must always be the same (e.g. two spaces) and structurally correctly represent what you want to achieve.

Therefore, please check the content of this file again.

**Comment by gmt-it** [comment]
Hello Stephan.

The options are now displayed. The css file is not included. I have now helped myself by including an scss file in my site set. Now I am still looking for the reason why my icons can be selected under Icon Set [page_icon_enable] but are not adopted. Everything works in RTE.

**Comment by stephankellermayr** [comment]
Since in your case it seems to be a very individual issue, rather than a possible bug or misbehavior, I would suggest that we continue communication via email.

What you seem to need is development help, so I'm closing this issue because Github is not really a support forum.

Also, it would be helpful to have a closer look at the whole extension.

Thanks for your understanding!
