### ISSUE TITLE
Header/All Partial breaks header_position setting

### ISSUE THREAD

**Issue by SicorDev** [quellenform/t3x-iconpack#30]
Hello there,

see subject. There's commas missing at the end of the three lines setting the positionClass attribute.

You also might consider my variant of handling the attribute. I'm eliminating Copy & Paste of the inline fluid with a variable:

<f:variable name="positionClass" value="{f:if(condition: data.header_position, then: 'ce-headline-{data.header_position}')}"/>

Then it's just thrice:
positionClass: positionClass,

Greetings,
Manuel

**Comment by stephankellermayr** [comment]
Thank you for your feedback and for reading it carefully! ...will be updated/corrected by me shortly.

All the best!
