### ISSUE TITLE
After Cache clearing: Button LinkButton is not valid

### ISSUE THREAD

**Issue by SicorDev** [quellenform/t3x-iconpack#5]
Hi there,

we have the backend running on German language on TYPO3 11.5.28 with the current TER relelase of iconpack.

Every time we cleared the Cache and then tried to edit a page or content element, we got an Exception when the core tried to add a button to the Toolbar. It is not valid, because the title was missing. After some core debugging, we figured that iconpack is killing the (working!) core language service in this situation.

Please consider changing IconpackProvider::getTranslatedLabel to this:

protected function getTranslatedLabel(string $label, ?string $default = ''): string
{
    //$GLOBALS['LANG'] = GeneralUtility::makeInstance(LanguageService::class);
    return !empty($label) ? $GLOBALS['LANG']->sL($label) : $default;
}

Not sure why you are making a new instance? It's already there :-)

Greetings,
Manuel

**Comment by stephankellermayr** [comment]
Thank you for your feedback and efforts, but unfortunately I cannot reproduce this bug.

This text passage does not exist in the code, at least not in versions 0.1.2-0.3.0 and also not in the current version in TER.

Which version of iconpack are you using?
Can you please check this again or give me more details?

**Comment by SicorDev** [comment]
Aha, okay. We're still using iconpack 0.2.1, I didn't see you uploaded a new version yesterday.

**Comment by SicorDev** [comment]
Oh dear... it was all my own fault I guess. You're right the problem is not from iconpack, it's me :-)
Please excuse the false report.

**Comment by stephankellermayr** [comment]
> Oh dear... it was all my own fault I guess. You're right the problem is not from iconpack, it's me :-) Please excuse the false report.

All is well, no harm done! I am grateful for any feedback, and after all, I can also make mistakes. Thanks anyway!

**Comment by SicorDev** [comment]
This extension is so cool! I wish mask would also use it, so it was the only Extension required for Font Awesome or other icon packs👍

**Comment by stephankellermayr** [comment]
@SicorDev Thank you for the praise! I think the only way that other extensions use *EXT:iconpack* is that more people use it. Most people don't even know about it yet, and many don't understand what exactly it does. Maybe it would be helpful to write some tutorials about it and to present the extension in videos. ...but unfortunately I don't have much time for that.
